packages:
  - packages/*
  - tooling/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

catalog:
  '@hookform/resolvers': 5.4.0
  '@tanstack/react-form': 1.33.5
  react-hook-form: 7.89.0
  '@kizlo/woocommerce': ^0.14.0
  '@tanstack/react-query': ^5.102.0
  '@testing-library/react': ^16.3.3
  '@types/node': ^22.18.12
  happy-dom: ^20.14.5
  kizlo: ^0.26.0
  nuqs: ^2.10.0
  tsdown: ^0.15.6
  typescript: ^5.9.3
  use-debounce: ^10.1.1
  vitest: ^3.2.4

catalogs:
  react19:
    react: ^19.2.3
    react-dom: ^19.2.3
    '@types/react': ^19.2.3
    '@types/react-dom': ^19.2.3

minimumReleaseAgeExclude:
  - kizlo@0.26.0
  - '@kizlo/woocommerce@0.14.0'
  - nanostores@1.5.5

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
